name: music_player_ui
description: A Flutter demo of a music player UI.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/songs.json
